import type { MatchLevel } from './chapter1';

// 3 cols × 4 rows = 12 cards = 6 pairs (3×3=9 is odd and can't form pairs)

const LEVELS: MatchLevel[] = [
  {
    id: 1, title: 'Happy or Sad?', instruction: 'Match the feelings!', mascot: 'HappyFace', cols: 3,
    cards: [
      { id: 'hap-a', pairId: 'hap', emoji: '😊', label: 'Happy',     color: '#F9A825' },
      { id: 'hap-b', pairId: 'hap', emoji: '😊', label: 'Happy',     color: '#F9A825' },
      { id: 'sad-a', pairId: 'sad', emoji: '😢', label: 'Sad',       color: '#1565C0' },
      { id: 'sad-b', pairId: 'sad', emoji: '😢', label: 'Sad',       color: '#1565C0' },
      { id: 'ang-a', pairId: 'ang', emoji: '😠', label: 'Angry',     color: '#E53935' },
      { id: 'ang-b', pairId: 'ang', emoji: '😠', label: 'Angry',     color: '#E53935' },
      { id: 'sur-a', pairId: 'sur', emoji: '😲', label: 'Surprised', color: '#7B1FA2' },
      { id: 'sur-b', pairId: 'sur', emoji: '😲', label: 'Surprised', color: '#7B1FA2' },
      { id: 'sca-a', pairId: 'sca', emoji: '😨', label: 'Scared',    color: '#00838F' },
      { id: 'sca-b', pairId: 'sca', emoji: '😨', label: 'Scared',    color: '#00838F' },
      { id: 'sle-a', pairId: 'sle', emoji: '😴', label: 'Sleepy',    color: '#546E7A' },
      { id: 'sle-b', pairId: 'sle', emoji: '😴', label: 'Sleepy',    color: '#546E7A' },
    ],
  },
  {
    id: 2, title: 'Silly Faces', instruction: 'Find the silly face pairs!', mascot: 'SillyFace', cols: 3,
    cards: [
      { id: 'sil-a', pairId: 'sil', emoji: '😜', label: 'Silly',     color: '#AB47BC' },
      { id: 'sil-b', pairId: 'sil', emoji: '😜', label: 'Silly',     color: '#AB47BC' },
      { id: 'coo-a', pairId: 'coo', emoji: '😎', label: 'Cool',      color: '#0288D1' },
      { id: 'coo-b', pairId: 'coo', emoji: '😎', label: 'Cool',      color: '#0288D1' },
      { id: 'lov-a', pairId: 'lov', emoji: '🥰', label: 'Loved',     color: '#E91E63' },
      { id: 'lov-b', pairId: 'lov', emoji: '🥰', label: 'Loved',     color: '#E91E63' },
      { id: 'thi-a', pairId: 'thi', emoji: '🤔', label: 'Thinking',  color: '#F9A825' },
      { id: 'thi-b', pairId: 'thi', emoji: '🤔', label: 'Thinking',  color: '#F9A825' },
      { id: 'wow-a', pairId: 'wow', emoji: '🤩', label: 'Wow',       color: '#2196F3' },
      { id: 'wow-b', pairId: 'wow', emoji: '🤩', label: 'Wow',       color: '#2196F3' },
      { id: 'shy-a', pairId: 'shy', emoji: '🫣', label: 'Shy',       color: '#009688' },
      { id: 'shy-b', pairId: 'shy', emoji: '🫣', label: 'Shy',       color: '#009688' },
    ],
  },
  {
    id: 3, title: 'Feeling Sick', instruction: 'Match the not-so-good feelings!', mascot: 'SickFace', cols: 3,
    cards: [
      { id: 'sic-a', pairId: 'sic', emoji: '🤒', label: 'Sick',      color: '#78909C' },
      { id: 'sic-b', pairId: 'sic', emoji: '🤒', label: 'Sick',      color: '#78909C' },
      { id: 'bor-a', pairId: 'bor', emoji: '😑', label: 'Bored',     color: '#8BC34A' },
      { id: 'bor-b', pairId: 'bor', emoji: '😑', label: 'Bored',     color: '#8BC34A' },
      { id: 'wor-a', pairId: 'wor', emoji: '😟', label: 'Worried',   color: '#FF7043' },
      { id: 'wor-b', pairId: 'wor', emoji: '😟', label: 'Worried',   color: '#FF7043' },
      { id: 'con-a', pairId: 'con', emoji: '😖', label: 'Confused',  color: '#7E57C2' },
      { id: 'con-b', pairId: 'con', emoji: '😖', label: 'Confused',  color: '#7E57C2' },
      { id: 'tir-a', pairId: 'tir', emoji: '😩', label: 'Tired',     color: '#8D6E63' },
      { id: 'tir-b', pairId: 'tir', emoji: '😩', label: 'Tired',     color: '#8D6E63' },
      { id: 'hug-a', pairId: 'hug', emoji: '🤗', label: 'Hugging',   color: '#FF8F00' },
      { id: 'hug-b', pairId: 'hug', emoji: '🤗', label: 'Hugging',   color: '#FF8F00' },
    ],
  },
  {
    id: 4, title: 'Big Feelings', instruction: 'Match all the big feelings!', mascot: 'ExcitedFace', cols: 3,
    cards: [
      { id: 'exc-a', pairId: 'exc', emoji: '🤪', label: 'Excited',   color: '#FF5722' },
      { id: 'exc-b', pairId: 'exc', emoji: '🤪', label: 'Excited',   color: '#FF5722' },
      { id: 'pro-a', pairId: 'pro', emoji: '😤', label: 'Proud',     color: '#7B1FA2' },
      { id: 'pro-b', pairId: 'pro', emoji: '😤', label: 'Proud',     color: '#7B1FA2' },
      { id: 'gra-a', pairId: 'gra', emoji: '🥹', label: 'Grateful',  color: '#E91E63' },
      { id: 'gra-b', pairId: 'gra', emoji: '🥹', label: 'Grateful',  color: '#E91E63' },
      { id: 'pai-a', pairId: 'pai', emoji: '😣', label: 'In Pain',   color: '#C62828' },
      { id: 'pai-b', pairId: 'pai', emoji: '😣', label: 'In Pain',   color: '#C62828' },
      { id: 'dre-a', pairId: 'dre', emoji: '😪', label: 'Dreamy',    color: '#5C6BC0' },
      { id: 'dre-b', pairId: 'dre', emoji: '😪', label: 'Dreamy',    color: '#5C6BC0' },
      { id: 'par-a', pairId: 'par', emoji: '🥳', label: 'Party',     color: '#2196F3' },
      { id: 'par-b', pairId: 'par', emoji: '🥳', label: 'Party',     color: '#2196F3' },
    ],
  },
  {
    id: 5, title: 'Mixed Emotions', instruction: 'How are you feeling?', mascot: 'NervousFace', cols: 3,
    cards: [
      { id: 'fre-a', pairId: 'fre', emoji: '😬', label: 'Nervous',   color: '#78909C' },
      { id: 'fre-b', pairId: 'fre', emoji: '😬', label: 'Nervous',   color: '#78909C' },
      { id: 'rel-a', pairId: 'rel', emoji: '😌', label: 'Relaxed',   color: '#81C784' },
      { id: 'rel-b', pairId: 'rel', emoji: '😌', label: 'Relaxed',   color: '#81C784' },
      { id: 'pla-a', pairId: 'pla', emoji: '😏', label: 'Playful',   color: '#FF8F00' },
      { id: 'pla-b', pairId: 'pla', emoji: '😏', label: 'Playful',   color: '#FF8F00' },
      { id: 'ouc-a', pairId: 'ouc', emoji: '🤕', label: 'Ouch',      color: '#EF5350' },
      { id: 'ouc-b', pairId: 'ouc', emoji: '🤕', label: 'Ouch',      color: '#EF5350' },
      { id: 'diz-a', pairId: 'diz', emoji: '😵', label: 'Dizzy',     color: '#5C6BC0' },
      { id: 'diz-b', pairId: 'diz', emoji: '😵', label: 'Dizzy',     color: '#5C6BC0' },
      { id: 'gig-a', pairId: 'gig', emoji: '🤭', label: 'Giggling',  color: '#F48FB1' },
      { id: 'gig-b', pairId: 'gig', emoji: '🤭', label: 'Giggling',  color: '#F48FB1' },
    ],
  },
  {
    id: 6, title: 'Emotion Expert', instruction: 'You know all the feelings!', mascot: 'CoolFace', cols: 3,
    cards: [
      { id: 'cla-a', pairId: 'cla', emoji: '👏', label: 'Clapping',  color: '#F9A825' },
      { id: 'cla-b', pairId: 'cla', emoji: '👏', label: 'Clapping',  color: '#F9A825' },
      { id: 'fis-a', pairId: 'fis', emoji: '✊', label: 'Strong',    color: '#E53935' },
      { id: 'fis-b', pairId: 'fis', emoji: '✊', label: 'Strong',    color: '#E53935' },
      { id: 'thu-a', pairId: 'thu', emoji: '👍', label: 'Great',     color: '#2E7D32' },
      { id: 'thu-b', pairId: 'thu', emoji: '👍', label: 'Great',     color: '#2E7D32' },
      { id: 'wav-a', pairId: 'wav', emoji: '👋', label: 'Waving',    color: '#0288D1' },
      { id: 'wav-b', pairId: 'wav', emoji: '👋', label: 'Waving',    color: '#0288D1' },
      { id: 'hrt-a', pairId: 'hrt', emoji: '❤️', label: 'Love',      color: '#E91E63' },
      { id: 'hrt-b', pairId: 'hrt', emoji: '❤️', label: 'Love',      color: '#E91E63' },
      { id: 'sta-a', pairId: 'sta', emoji: '⭐', label: 'Star',      color: '#E53935' },
      { id: 'sta-b', pairId: 'sta', emoji: '⭐', label: 'Star',      color: '#E53935' },
    ],
  },
];

export default LEVELS;
